### ISSUE TITLE
Ability to resize nodes? 

### ISSUE THREAD

**Issue by oakif** [jac3km4/comfyweb#1]
Would it be possible to resize different nodes? For example, let's say I wanted to expand the CLIPTextEncode text boxes so that I could see more of the text within the box? 

![image](https://user-images.githubusercontent.com/48932412/224410640-68c7ddd9-135f-461c-b313-955a836cebbb.png)

**Comment by jac3km4** [comment]
resizing nodes is a bit tricky, but I've added textbox resizing in the meantime @oakif

**Comment by jac3km4** [comment]
closing because the UI has been re-worked
