### ISSUE TITLE
Align text input boxes

### ISSUE THREAD

**Issue by oakif** [jac3km4/comfyweb#3]
I think in most UIs text input boxes are aligned. Would it be possible to do it here as well? It would give the UI a cleaner look! 

<img width="616" alt="image" src="https://user-images.githubusercontent.com/48932412/224411833-1cd43427-ac95-44b5-bc58-f02bab4d9ee0.png">

**Comment by jac3km4** [comment]
Do you mean like a grid/table? The annoying thing about that is that it would end up wasting space for some of the widgets that have long labels.

**Comment by oakif** [comment]
You're totally right about that since it would depend on the length of the longest key string. I'm trying to think of a good solution/compromise that doesn't have uneven selection boxes, but that wouldn't take up significantly more space than this option (which seems to be the most space-efficient). I'm just saying it because I've never seen a "professional" UI with text boxes like this. I'll update if I have any good ideas

**Comment by jac3km4** [comment]
closing because the UI has been re-worked
