### ISSUE TITLE
Better way to show batch images

### ISSUE THREAD

**Issue by oakif** [jac3km4/comfyweb#4]
I tried creating a set of four portrait batch images, but the way they were laid out, it looks like it's really hard to browse through the images. Take a look at the example in the screenshot. I think it might be an easier idea to have a mini "gallery" in the SaveImage node with arrow keys to click when you want to look through the images, or else it becomes very hard to look through. 

![image](https://user-images.githubusercontent.com/48932412/224412279-8cc91a3c-bcff-406a-ae13-479f2e8bff05.png)

**Comment by jac3km4** [comment]
I've pushed a change that adds a unified image viewer for the gallery and SaveImage

**Comment by jac3km4** [comment]
@oakif let me know if the new viewer solves your issue, I'll close this ticket if it does

**Comment by jac3km4** [comment]
closing because the UI has been re-worked
