### ISSUE TITLE
Bottom bar should be automatically expanded when tab is selected

### ISSUE THREAD

**Issue by oakif** [jac3km4/comfyweb#5]
The bottom bar should be automatically expanded when you click on one of the tabs. This I believe is the typical behavior for most UIs, and saved a step of having to expand out the bottom bar again. 

<img width="354" alt="image" src="https://user-images.githubusercontent.com/48932412/224412524-372bdd62-aae5-4e7b-ab37-ab0f43b5b8bc.png">

**Comment by jac3km4** [comment]
Thanks for the suggestions. I agree, I think expanding it on tab change would reasonable.

**Comment by jac3km4** [comment]
should be fixed now
