### ISSUE TITLE
How to use this alternative UI? 

### ISSUE THREAD

**Issue by VOOM108** [jac3km4/comfyweb#8]
I am kind of lost about how to use this alternative UI. I cloned the repo (git clone -b new-ui-and-feats https://github.com/jac3km4/ComfyUI) and followed the instructions... Running it works, but it looks and works exactly like the ComfyUI this was forked from.

**Comment by jac3km4** [comment]
Try running just the commands below
```psh
git clone -b new-ui-and-feats https://github.com/jac3km4/ComfyUI altcomfyui
cd altcomfyui
python main.py
```
Also make sure you're not running any other instances of ComfyUI at the same time.

**Comment by VOOM108** [comment]
I was trying to execute the script with a batchfile as the original UI does. Now it seems there are two issues: 1. this only works in powershell, not in a regular command-window 2. I have to run "E:\...\.venv\Scripts\Activate.ps1" every time first (in order to not have another python environment installed) and then "python main.py"

If I do that manually in powershell, it works! 

(Is there a way to do this with a batch file?)

**Comment by VOOM108** [comment]
What does this tell me? 

```
got prompt
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
Restored from E:\ComfyWeb\models\vae\vae-ft-mse-840000-ema-pruned.ckpt
   | Making attention of type 'vanilla' with 512 in_channels
   | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
   | Making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "E:\ComfyWeb\execution.py", line 174, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "E:\ComfyWeb\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "E:\ComfyWeb\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "E:\ComfyWeb\execution.py", line 54, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "E:\ComfyWeb\execution.py", line 63, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "E:\ComfyWeb\nodes.py", line 243, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=CheckpointLoader.embedding_directory)
  File "E:\ComfyWeb\comfy\sd.py", line 853, in load_checkpoint_guess_config
    model = instantiate_from_config(model_config)
  File "E:\ComfyWeb\comfy\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
TypeError: LatentDiffusion.__init__() missing 3 required positional arguments: 'first_stage_config', 'cond_stage_config', and 'personalization_config'
```

**Comment by jac3km4** [comment]
Try to update the branch, it's been out of date

**Comment by VOOM108** [comment]
I did `git pull <repo> master`, and it is up-to-date now, but the same error occurs....

**Comment by VOOM108** [comment]
Since the UI is there, just the generation does not work, one comment: when adding new nodes via the box at the bottom, which is the only way, the nodes appear behind that box. And the box itself cannot be moved. So one has to pull the new node out from under there by dragging the whole canvas. Could there be two ways to add the nodes - keep the context menu as well - and could the box at the bottom maybe be dragged, minimized and resizable for more flexibility?

**Comment by jac3km4** [comment]
You shouldn't pull master, the new UI is on the new-ui-and-feats branch. One easy way to update is `git fetch` + `git reset origin/new-ui-and-feats`

**Comment by jac3km4** [comment]
I'll look into creating an install package later, at the moment keeping it up to date requires a bit of git knowledge

**Comment by VOOM108** [comment]
Thank you. (I have a hard time to understand git, but it's getting better) :)

**Comment by VOOM108** [comment]
The same error still remains, though...

**Comment by jac3km4** [comment]
Can you save the workflow to a JSON file and upload it here?

**Comment by VOOM108** [comment]
I get this with any workflow, and I did not really change much from the default workflow, not even the prompt.... 
[workflows.zip](https://github.com/jac3km4/comfyweb/files/10984197/workflows.zip)

**Comment by jac3km4** [comment]
Have you edited any of the files in `models/configs`? The error is coming from ComfyUI and it's saying that one of the YAML files in that directory is missing required fields (`first_stage_config`). All files there should have these fields.

**Comment by VOOM108** [comment]
No, I have not touched that folder at all...

**Comment by jac3km4** [comment]
The error makes it seem like some of the files you have locally are out of sync.
Can you have a look at lines 523-535 in `comfy/ldm/models/diffusion/ddpm.py`
These lines look like this on my branch and ComfyUI master:
```python
    def __init__(self,
                 first_stage_config={},
                 cond_stage_config={},
                 num_timesteps_cond=None,
                 cond_stage_key="image",
                 cond_stage_trainable=False,
                 concat_mode=True,
                 cond_stage_forward=None,
                 conditioning_key=None,
                 scale_factor=1.0,
                 scale_by_std=False,
                 force_null_conditioning=False,
                 *args, **kwargs):
```
Can you verify that's what you've got as well? Especially the `first_stage_config={}` part.

**Comment by VOOM108** [comment]
![image](https://user-images.githubusercontent.com/16562946/225445609-a6d24e39-adec-4ee6-863f-e8debd3dff31.png)

**Comment by jac3km4** [comment]
OK, to avoid dealing with the specifics of your installation, assuming you have a working ComfyUI, you can just extract the frontend bundle into the `web` dir of the standard ComfyUI installation:
[web.zip](https://github.com/jac3km4/comfyweb/files/10984583/web.zip)
It should work as long as your ComfyUI installation isn't broken.
I'll make this an installation option later on.

**Comment by VOOM108** [comment]
That works :) 

The only thing I now encounter, is that -1 as a random seed does not work. Should it? If I put in a value for a seed myself, it works. 

got prompt
Failed to validate prompt for output 6 Value smaller than min. KSampler, seed
output will be ignored
invalid prompt: Prompt has no properly connected outputs
 Value smaller than min. KSampler, seed

**Comment by jac3km4** [comment]
Yes, random seed will be broken for you, because it requires a change from my fork, which you are no longer using
You can maybe switch back to the fork once there's an easier installation option, in the meantime I'm gonna close this issue

**Comment by VOOM108** [comment]
I tried several times to install fresh, following the instructions to the letter without trying to use the .venv from another SD UI

Between 
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
and 
pip install xformers

I get that cu117 requires torch 2.0.0 so it installs that
xformers uninstalls torch 2.0.0 and installs 1.13.1 because it does not work with 2.0.0
then cu117 does not work because it needs 2.0.0

I then used: 
pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117

...and now it finally runs!

**Comment by VOOM108** [comment]
First I had tried to install xformers for torch 2.0.0, but that produced new errors I could not resolve...
